apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: django-hello-world
          image: slagomarsino/django-hello-world
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: django
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: supersecretpassword

      restartPolicy: Never
  backoffLimit: 5
