apiVersion: v1
kind: Service
metadata:
  name: django-hello-world
  labels:
    app: django-hello-world
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: django-hello-world
